apiVersion: v1
kind: Service
metadata:
  name: mpcalc-hub-personal-service
spec:  
  type: NodePort
  selector:
    app: mpcalc-hub-personal
  ports:
    - port: 80
      targetPort: 5056
      nodePort: 32001
