apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpcalc-deleter-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpcalc-deleter-producer
  template:
    metadata:
      labels:
        app: mpcalc-deleter-producer
    spec:
      containers:
      - name: mpcalc-deleter-producer
        image: mpcalc-deleter-producer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mpcalc-config
