apiVersion: v1
kind: Service
metadata:
  name: mpcalc-deleter-producer-service
spec:
  type: NodePort
  selector:
    app: mpcalc-deleter-producer
  ports:
    - port: 80
      targetPort: 5024
      nodePort: 32003
