global:
  scrape_interval: 5s  # Intervalo de coleta das métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
