apiVersion: v1
kind: Service
metadata:
  name: mpcalc-updater-producer-service
spec:
  type: NodePort
  selector:
    app: mpcalc-updater-producer
  ports:
    - port: 80
      targetPort: 5023
      nodePort: 32002
