apiVersion: v1
kind: Service
metadata:
  name: mpazure-functions-service
spec:
  selector:
    app: mpazure-functions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
